### ISSUE TITLE
building and starting of Nextcloud-Signal Docker Cotainers Fails

### ISSUE THREAD

**Issue by Still-not-found** [deeztek/deeztek-docker#3] opened 2022-08-25 06:21 UTC
after it auto generates the shared key and secret key , it throws an error 
Building Nextcloud-Signal Docker Containers...                                                                                                      [FAIL] 
Starting Nextcloud-Signal Docker Containers...                                                                                                      [FAIL]

How to resolve this issue? please share any ideas to resolve this  issue

**Comment by deeztek** [comment] 2022-08-25 10:48
There should be an **install_log-[timestamp].log** file in the same directory you started the install script. Take a look in that file for the cause of the error. You can always post here ensuring that you remove any sensitive info.

thanks

**Comment by Still-not-found** [comment] 2022-08-26 05:13
Thank you sir for your response .

**Comment by Still-not-found** [comment] 2022-08-26 11:22
Sir,actually the  "ubuntu_install_nextcloud_signal.sh" script fails to build and deploy these containers that are mentioned below ,would you please suggest a solution for this?
* nextcloud_spreed_nginx
* nextcloud_spreed_backend
* nextcloud_spreed_janus
* nextcloud_spreed_coturn
* nextcloud_spreed_nats
* nextcloud_spreed_certbot.

**Comment by deeztek** [comment] 2022-08-26 11:29
I'm going to need more information than simply "script fails to build and deploy". What does the install log say? Do you have docker-compose installed?

**Comment by Still-not-found** [comment] 2022-08-28 11:05
Yes sir, docker-compose is installed in my ubuntu 20.04 server and I also
need your help to clarify my doubt, if this signaling server is perfectly
installed through that how many active participants can i host in a single
videoconference using this signaling server? Please let me know sir.

                     Thank you

**Comment by deeztek** [comment] 2022-08-28 11:42
The only limiting factor should be your signaling server resources.

**Comment by Still-not-found** [comment] 2022-09-25 17:11
Sorry , I can't understand why this kind of error is thrown , could you
able to send me some example screenshots of this nextcloud-signal Docker,so
that i will be able to get an idea to solve this problem.

**Comment by deeztek** [comment] 2022-09-26 12:02
As previously mentioned:

There should be an **install_log-[timestamp].log** file in the same directory you started the install script. Take a look in that file for the cause of the error. You can always post here ensuring that you remove any sensitive info.

Unless you provide the install log, I cannot help you.

**Comment by Still-not-found** [comment] 2022-10-11 09:14
Thank you for the clarification,sir.

**Comment by StephanEto** [comment] 2022-11-22 08:42
Hi, 
i have the same issue at the same position run with Ubuntu 20.04. All Prequisites are okay. 
Following entry in the install_log file:
`Building Nextcloud-Signal Docker Containers
build path /opt/nextcloud-spreed-signaling/docker/coturn either does not exist, is not accessible, or is not a valid URL.
`
Thank you!

**Comment by deeztek** [comment] 2022-11-22 13:37
There should be an **install_log-[timestamp].log** file in the same directory you started the install script. Please provide script so that I can take a look.

**Comment by StephanEto** [comment] 2022-11-22 14:15
Here is the script:
[install_log-11-22-2022-0847.log](https://github.com/deeztek/deeztek-docker/files/10068164/install_log-11-22-2022-0847.log)

**Comment by deeztek** [comment] 2022-11-22 16:26
Thank you. Let me take a look. There also seems to be a change with the nextcloud-spreed repo and the way it the docker installation works now. Let me  work on it and get back to you asap.

**Comment by deeztek** [comment] 2022-11-23 15:24
Commit [https://github.com/deeztek/deeztek-docker/commit/b017a6e31e5b89172e7047d5a3e1d53b49ef0a5c](https://github.com/deeztek/deeztek-docker/commit/b017a6e31e5b89172e7047d5a3e1d53b49ef0a5c) should fix all the issues you are experiencing.

**How to re-deploy:**

- bring down any containers that were created/started from the /opt/nextcloud-spreed-signaling directory: **docker-compose down**
- remove any volumes if they exist (most likely will be removed after the docker-compose down command)
- remove the spreed network that was previously created: **docker network rm spreed**
- remove the /opt/nextcloud-spreed-signaling directory: **rm -rf /opt/nextcloud-spreed-signaling**
- remove the deeztek-docker repository
- git clone the deeztek-docker repository
- run the install script: **sudo bash ubuntu_install_nextcloud_signal.sh**

This was tested on Ubuntu 18.04 LTS but they shouldn't be a problem with newer version. Please let me know if any. **Bonus:** this now works with newest version of Nextcloud.

**Comment by StephanEto** [comment] 2022-11-24 08:42
Hey deeztek,

thank you for update the script! Please check out line 462 in ubuntu_install_nextcloud_signal.sh:
I had to change /usr/local/bin/docker to /usr/bin/docker . Then it worked perfectly.
Best regards!

**Comment by deeztek** [comment] 2022-11-24 11:01
Thanks for the feedback! Fixed with [https://github.com/deeztek/deeztek-docker/commit/136a43b44658640c27df4aa55d2731ca6f4ca7ba](https://github.com/deeztek/deeztek-docker/commit/136a43b44658640c27df4aa55d2731ca6f4ca7ba).

**Closed as completed by deeztek** 2022-11-24 11:01 UTC
Labels: help wanted
